### ISSUE TITLE
Combine resizing with other options like webp

### ISSUE THREAD

**Issue by mastef** [cyrilwanner/next-optimized-images#127]
Would it be possible to stack `resize` with another parameter like `webp`? Currently it seems it's either or. Right now I can only do this in css :

```css
.webp .bgimage {
	background-image: url('../static/images/bg.jpg?webp'); // will be over-sized
}
.no-webp .bgimage {
	background-image: url('../static/images/bg.jpg?resize&size=520');
}
```
Ideally I'd like to do this  : 
```css
.webp .bgimage {
	background-image: url('../static/images/bg.jpg?webp&resize&size=520');
}
.no-webp .bgimage {
	background-image: url('../static/images/bg.jpg?resize&size=520');
}
```
