### ISSUE TITLE
webp for background-image

### ISSUE THREAD

**Issue by pabloow** [cyrilwanner/next-optimized-images#52]
How can I achieve something similar to:

'<picture>
    <source srcSet={require('./images/my-image.jpg?webp')} type="image/webp" />
    <source srcSet={require('./images/my-image.jpg')} type="image/jpeg" />
    <img src={require('./images/my-image.jpg')} />
  </picture>'

for a background-image? Is it currently possible?

**Comment by cyrilwanner** [comment]
Hi @pabloow 
Sorry for the late response, I didn't have much time in the last few weeks.

Unfortunately, it is not possible with pure CSS.
The most suggested workaround is to detect if your browser supports WebP in JavaScript (e.g. with Modernizr) and then add, for example, a `.webp` class to your body.
In the CSS you can then use the correct image type like this:
```css
body.webp .mydiv {
  background-image: url('./images/my-image.jpg?webp');
}
body:not(.webp) .mydiv {
  background-image: url('./images/my-image.jpg');
}
```

*Examples are from https://stackoverflow.com/questions/47607201/webp-image-fall-back and https://css-tricks.com/using-webp-images/*

In react, you could also have a helper function and then choose the correct classname:
```jsx
import { supportsWebp } from './helpers'

export default () => (
	<div className={supportsWebp() ? 'webp-bg' : 'fallback-bg'}>
		...
	</div>
);
```
